predictions: /path/to/concept_predictions.jsonl
labels_csv: data/local_data/chexpert-5x200-val-meta.csv
chexpert5: true
output_dir: outputs/cbm_label_head_demo
epochs: 5
batch_size: 64
learning_rate: 0.001
weight_decay: 0.0001
train_fraction: 0.8
seed: 42
device: cuda
early_stop_patience: 6
early_stop_min_delta: 0.0005
