dataset_name: mimic_cxr
labels_csv: /path/to/labels.csv
metadata_csv: /path/to/metadata.csv
image_root: /path/to/images
label_columns:
  - Cardiomegaly
  - Edema
  - Consolidation
  - Pleural Effusion
  - Atelectasis
chexpert5: true
output_dir: outputs/clip_finetune_example
epochs: 5
batch_size: 32
learning_rate: 0.0002
weight_decay: 0.0001
train_fraction: 0.8
device: cuda
clip_checkpoint: /path/to/r50_m.tar
